repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.13.1"
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: # These dependencies are needed for mypy to work properly (mostly for stubs, I think)
          - pydantic>=2.11.0,<3.0.0
          - bcrypt>=4.3.0,<5.0.0
          - python-jose>=3.5.0,<4.0.0
          - types-python-jose>=3.5.0,<4.0.0
