"""add revoked to participation

Revision ID: 5b1324341fac
Revises: 602defcad4bf
Create Date: 2025-12-19 09:11:08.349723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1324341fac'
down_revision: Union[str, Sequence[str], None] = '602defcad4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participations', sa.Column('revoked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participations', 'revoked')
    # ### end Alembic commands ###
