"""Add conferences, participations, participants

Revision ID: 602defcad4bf
Revises: db2b7a2b032a
Create Date: 2025-10-19 23:36:19.143754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602defcad4bf'
down_revision: Union[str, Sequence[str], None] = 'db2b7a2b032a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conferences',
    sa.Column('conference_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=False),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('registration_deadline', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CANCELLED', 'COMPLETED', name='conferencestatus', native_enum=False), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('conference_id')
    )
    op.create_table('participants',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('patronymic', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('home_number', sa.String(length=20), nullable=True),
    sa.Column('academic_degree', sa.Enum('NONE', 'CANDIDATE', 'DOCTOR', name='academicdegree', native_enum=False), nullable=True),
    sa.Column('academic_title', sa.Enum('NONE', 'DOCENT', 'PROFESSOR', name='academictitle', native_enum=False), nullable=True),
    sa.Column('research_area', sa.Enum('NONE', 'MATHEMATICS', 'PHYSICS', 'COMPUTER_SCIENCE', 'BIOLOGY', 'OTHER', name='researcharea', native_enum=False), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('street_address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('participations',
    sa.Column('conference_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('SPEAKER', 'PARTICIPANT', name='role', native_enum=False), nullable=False),
    sa.Column('first_invitation_date', sa.Date(), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('submission_topic', sa.String(length=500), nullable=True),
    sa.Column('submission_thesis_received', sa.Boolean(), nullable=True),
    sa.Column('second_invitation_date', sa.Date(), nullable=True),
    sa.Column('fee_payment_date', sa.Date(), nullable=True),
    sa.Column('fee_amount', sa.Float(), nullable=True),
    sa.Column('fee_currency', sa.Enum('RUB', 'USD', 'EUR', name='currency', native_enum=False), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('needs_hotel', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.conference_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conference_id', 'participant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participations')
    op.drop_table('participants')
    op.drop_table('conferences')
    # ### end Alembic commands ###
